package com.ibm.maf.rmi;

// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

public final class MAFAgentSystem_RMIImpl_Stub extends
java.rmi.server.RemoteStub implements
com.ibm.maf.rmi.MAFAgentSystem_RMI, java.rmi.Remote {
	private static final long serialVersionUID = 2;

	private static java.lang.reflect.Method $method_create_agent_0;
	private static java.lang.reflect.Method $method_fetch_class_1;
	private static java.lang.reflect.Method $method_find_nearby_agent_system_of_profile_2;
	private static java.lang.reflect.Method $method_get_MAFFinder_3;
	private static java.lang.reflect.Method $method_get_agent_status_4;
	private static java.lang.reflect.Method $method_get_agent_system_info_5;
	private static java.lang.reflect.Method $method_get_authinfo_6;
	private static java.lang.reflect.Method $method_list_all_agents_7;
	private static java.lang.reflect.Method $method_list_all_agents_of_authority_8;
	private static java.lang.reflect.Method $method_list_all_places_9;
	private static java.lang.reflect.Method $method_receive_agent_10;
	private static java.lang.reflect.Method $method_receive_future_message_11;
	private static java.lang.reflect.Method $method_receive_future_reply_12;
	private static java.lang.reflect.Method $method_receive_message_13;
	private static java.lang.reflect.Method $method_receive_oneway_message_14;
	private static java.lang.reflect.Method $method_resume_agent_15;
	private static java.lang.reflect.Method $method_retract_agent_16;
	private static java.lang.reflect.Method $method_suspend_agent_17;
	private static java.lang.reflect.Method $method_terminate_agent_18;

	static {
		try {
			$method_create_agent_0 = com.ibm.maf.rmi.MAFAgentSystem_RMI.class.getMethod("create_agent", new java.lang.Class[] {
					com.ibm.maf.Name.class, com.ibm.maf.AgentProfile.class,
					byte[].class, java.lang.String.class,
					java.lang.Object[].class, com.ibm.maf.ClassName[].class,
					java.lang.String.class,
					com.ibm.maf.rmi.MAFAgentSystem_RMI.class });
			$method_fetch_class_1 = com.ibm.maf.rmi.MAFAgentSystem_RMI.class.getMethod("fetch_class", new java.lang.Class[] {
					com.ibm.maf.ClassName[].class, java.lang.String.class,
					com.ibm.maf.AgentProfile.class });
			$method_find_nearby_agent_system_of_profile_2 = com.ibm.maf.rmi.MAFAgentSystem_RMI.class.getMethod("find_nearby_agent_system_of_profile", new java.lang.Class[] { com.ibm.maf.AgentProfile.class });
			$method_get_MAFFinder_3 = com.ibm.maf.rmi.MAFAgentSystem_RMI.class.getMethod("get_MAFFinder", new java.lang.Class[] {});
			$method_get_agent_status_4 = com.ibm.maf.rmi.MAFAgentSystem_RMI.class.getMethod("get_agent_status", new java.lang.Class[] { com.ibm.maf.Name.class });
			$method_get_agent_system_info_5 = com.ibm.maf.rmi.MAFAgentSystem_RMI.class.getMethod("get_agent_system_info", new java.lang.Class[] {});
			$method_get_authinfo_6 = com.ibm.maf.rmi.MAFAgentSystem_RMI.class.getMethod("get_authinfo", new java.lang.Class[] { com.ibm.maf.Name.class });
			$method_list_all_agents_7 = com.ibm.maf.rmi.MAFAgentSystem_RMI.class.getMethod("list_all_agents", new java.lang.Class[] {});
			$method_list_all_agents_of_authority_8 = com.ibm.maf.rmi.MAFAgentSystem_RMI.class.getMethod("list_all_agents_of_authority", new java.lang.Class[] { byte[].class });
			$method_list_all_places_9 = com.ibm.maf.rmi.MAFAgentSystem_RMI.class.getMethod("list_all_places", new java.lang.Class[] {});
			$method_receive_agent_10 = com.ibm.maf.rmi.MAFAgentSystem_RMI.class.getMethod("receive_agent", new java.lang.Class[] {
					com.ibm.maf.Name.class, com.ibm.maf.AgentProfile.class,
					byte[].class, java.lang.String.class,
					com.ibm.maf.ClassName[].class, java.lang.String.class,
					com.ibm.maf.rmi.MAFAgentSystem_RMI.class });
			$method_receive_future_message_11 = com.ibm.maf.rmi.MAFAgentSystem_RMI.class.getMethod("receive_future_message", new java.lang.Class[] {
					com.ibm.maf.Name.class, byte[].class,
					com.ibm.maf.rmi.MAFAgentSystem_RMI.class });
			$method_receive_future_reply_12 = com.ibm.maf.rmi.MAFAgentSystem_RMI.class.getMethod("receive_future_reply", new java.lang.Class[] {
					long.class, byte[].class });
			$method_receive_message_13 = com.ibm.maf.rmi.MAFAgentSystem_RMI.class.getMethod("receive_message", new java.lang.Class[] {
					com.ibm.maf.Name.class, byte[].class });
			$method_receive_oneway_message_14 = com.ibm.maf.rmi.MAFAgentSystem_RMI.class.getMethod("receive_oneway_message", new java.lang.Class[] {
					com.ibm.maf.Name.class, byte[].class });
			$method_resume_agent_15 = com.ibm.maf.rmi.MAFAgentSystem_RMI.class.getMethod("resume_agent", new java.lang.Class[] { com.ibm.maf.Name.class });
			$method_retract_agent_16 = com.ibm.maf.rmi.MAFAgentSystem_RMI.class.getMethod("retract_agent", new java.lang.Class[] { com.ibm.maf.Name.class });
			$method_suspend_agent_17 = com.ibm.maf.rmi.MAFAgentSystem_RMI.class.getMethod("suspend_agent", new java.lang.Class[] { com.ibm.maf.Name.class });
			$method_terminate_agent_18 = com.ibm.maf.rmi.MAFAgentSystem_RMI.class.getMethod("terminate_agent", new java.lang.Class[] { com.ibm.maf.Name.class });
		} catch (final java.lang.NoSuchMethodException e) {
			throw new java.lang.NoSuchMethodError("stub class initialization failed");
		}
	}

	// constructors
	public MAFAgentSystem_RMIImpl_Stub(final java.rmi.server.RemoteRef ref) {
		super(ref);
	}

	// methods from remote interfaces

	// implementation of create_agent(Name, AgentProfile, byte[], String,
	// Object[], ClassName[], String, MAFAgentSystem_RMI)
	@Override
	public com.ibm.maf.Name create_agent(
	                                     final com.ibm.maf.Name $param_Name_1,
	                                     final com.ibm.maf.AgentProfile $param_AgentProfile_2,
	                                     final byte[] $param_arrayOf_byte_3,
	                                     final java.lang.String $param_String_4,
	                                     final java.lang.Object[] $param_arrayOf_Object_5,
	                                     final com.ibm.maf.ClassName[] $param_arrayOf_ClassName_6,
	                                     final java.lang.String $param_String_7,
	                                     final com.ibm.maf.rmi.MAFAgentSystem_RMI $param_MAFAgentSystem_RMI_8)
	throws java.rmi.RemoteException {
		try {
			final Object $result = ref.invoke(this, $method_create_agent_0, new java.lang.Object[] {
					$param_Name_1, $param_AgentProfile_2,
					$param_arrayOf_byte_3, $param_String_4,
					$param_arrayOf_Object_5, $param_arrayOf_ClassName_6,
					$param_String_7, $param_MAFAgentSystem_RMI_8 }, -1866539144229465750L);

			return ((com.ibm.maf.Name) $result);
		} catch (final java.lang.RuntimeException e) {
			throw e;
		} catch (final java.rmi.RemoteException e) {
			throw e;
		} catch (final java.lang.Exception e) {
			throw new java.rmi.UnexpectedException("undeclared checked exception", e);
		}
	}

	// implementation of fetch_class(ClassName[], String, AgentProfile)
	@Override
	public byte[][] fetch_class(
	                            final com.ibm.maf.ClassName[] $param_arrayOf_ClassName_1,
	                            final java.lang.String $param_String_2,
	                            final com.ibm.maf.AgentProfile $param_AgentProfile_3)
	throws java.rmi.RemoteException {
		try {
			final Object $result = ref.invoke(this, $method_fetch_class_1, new java.lang.Object[] {
					$param_arrayOf_ClassName_1, $param_String_2,
					$param_AgentProfile_3 }, 7322722473633204589L);

			return ((byte[][]) $result);
		} catch (final java.lang.RuntimeException e) {
			throw e;
		} catch (final java.rmi.RemoteException e) {
			throw e;
		} catch (final java.lang.Exception e) {
			throw new java.rmi.UnexpectedException("undeclared checked exception", e);
		}
	}

	// implementation of find_nearby_agent_system_of_profile(AgentProfile)
	@Override
	public java.lang.String find_nearby_agent_system_of_profile(
	                                                            final com.ibm.maf.AgentProfile $param_AgentProfile_1)
	throws java.rmi.RemoteException {
		try {
			final Object $result = ref.invoke(this, $method_find_nearby_agent_system_of_profile_2, new java.lang.Object[] { $param_AgentProfile_1 }, -8908075601947263529L);

			return ((java.lang.String) $result);
		} catch (final java.lang.RuntimeException e) {
			throw e;
		} catch (final java.rmi.RemoteException e) {
			throw e;
		} catch (final java.lang.Exception e) {
			throw new java.rmi.UnexpectedException("undeclared checked exception", e);
		}
	}

	// implementation of get_agent_status(Name)
	@Override
	public com.ibm.maf.AgentStatus get_agent_status(
	                                                final com.ibm.maf.Name $param_Name_1)
	throws java.rmi.RemoteException {
		try {
			final Object $result = ref.invoke(this, $method_get_agent_status_4, new java.lang.Object[] { $param_Name_1 }, -2745466359323440760L);

			return ((com.ibm.maf.AgentStatus) $result);
		} catch (final java.lang.RuntimeException e) {
			throw e;
		} catch (final java.rmi.RemoteException e) {
			throw e;
		} catch (final java.lang.Exception e) {
			throw new java.rmi.UnexpectedException("undeclared checked exception", e);
		}
	}

	// implementation of get_agent_system_info()
	@Override
	public com.ibm.maf.AgentSystemInfo get_agent_system_info()
	throws java.rmi.RemoteException {
		try {
			final Object $result = ref.invoke(this, $method_get_agent_system_info_5, null, 8459926394242155418L);

			return ((com.ibm.maf.AgentSystemInfo) $result);
		} catch (final java.lang.RuntimeException e) {
			throw e;
		} catch (final java.rmi.RemoteException e) {
			throw e;
		} catch (final java.lang.Exception e) {
			throw new java.rmi.UnexpectedException("undeclared checked exception", e);
		}
	}

	// implementation of get_authinfo(Name)
	@Override
	public com.ibm.maf.AuthInfo get_authinfo(final com.ibm.maf.Name $param_Name_1)
	throws java.rmi.RemoteException {
		try {
			final Object $result = ref.invoke(this, $method_get_authinfo_6, new java.lang.Object[] { $param_Name_1 }, 1555346500431042527L);

			return ((com.ibm.maf.AuthInfo) $result);
		} catch (final java.lang.RuntimeException e) {
			throw e;
		} catch (final java.rmi.RemoteException e) {
			throw e;
		} catch (final java.lang.Exception e) {
			throw new java.rmi.UnexpectedException("undeclared checked exception", e);
		}
	}

	// implementation of get_MAFFinder()
	@Override
	public com.ibm.maf.MAFFinder get_MAFFinder()
	throws java.rmi.RemoteException {
		try {
			final Object $result = ref.invoke(this, $method_get_MAFFinder_3, null, 2335360634011898291L);

			return ((com.ibm.maf.MAFFinder) $result);
		} catch (final java.lang.RuntimeException e) {
			throw e;
		} catch (final java.rmi.RemoteException e) {
			throw e;
		} catch (final java.lang.Exception e) {
			throw new java.rmi.UnexpectedException("undeclared checked exception", e);
		}
	}

	// implementation of list_all_agents()
	@Override
	public com.ibm.maf.Name[] list_all_agents() throws java.rmi.RemoteException {
		try {
			final Object $result = ref.invoke(this, $method_list_all_agents_7, null, 8158779092947588092L);

			return ((com.ibm.maf.Name[]) $result);
		} catch (final java.lang.RuntimeException e) {
			throw e;
		} catch (final java.rmi.RemoteException e) {
			throw e;
		} catch (final java.lang.Exception e) {
			throw new java.rmi.UnexpectedException("undeclared checked exception", e);
		}
	}

	// implementation of list_all_agents_of_authority(byte[])
	@Override
	public com.ibm.maf.Name[] list_all_agents_of_authority(
	                                                       final byte[] $param_arrayOf_byte_1)
	throws java.rmi.RemoteException {
		try {
			final Object $result = ref.invoke(this, $method_list_all_agents_of_authority_8, new java.lang.Object[] { $param_arrayOf_byte_1 }, -6122543635398668412L);

			return ((com.ibm.maf.Name[]) $result);
		} catch (final java.lang.RuntimeException e) {
			throw e;
		} catch (final java.rmi.RemoteException e) {
			throw e;
		} catch (final java.lang.Exception e) {
			throw new java.rmi.UnexpectedException("undeclared checked exception", e);
		}
	}

	// implementation of list_all_places()
	@Override
	public java.lang.String[] list_all_places() throws java.rmi.RemoteException {
		try {
			final Object $result = ref.invoke(this, $method_list_all_places_9, null, 4337683576072117622L);

			return ((java.lang.String[]) $result);
		} catch (final java.lang.RuntimeException e) {
			throw e;
		} catch (final java.rmi.RemoteException e) {
			throw e;
		} catch (final java.lang.Exception e) {
			throw new java.rmi.UnexpectedException("undeclared checked exception", e);
		}
	}

	// implementation of receive_agent(Name, AgentProfile, byte[], String,
	// ClassName[], String, MAFAgentSystem_RMI)
	@Override
	public void receive_agent(
	                          final com.ibm.maf.Name $param_Name_1,
	                          final com.ibm.maf.AgentProfile $param_AgentProfile_2,
	                          final byte[] $param_arrayOf_byte_3,
	                          final java.lang.String $param_String_4,
	                          final com.ibm.maf.ClassName[] $param_arrayOf_ClassName_5,
	                          final java.lang.String $param_String_6,
	                          final com.ibm.maf.rmi.MAFAgentSystem_RMI $param_MAFAgentSystem_RMI_7)
	throws java.rmi.RemoteException {
		try {
			ref.invoke(this, $method_receive_agent_10, new java.lang.Object[] {
					$param_Name_1, $param_AgentProfile_2,
					$param_arrayOf_byte_3, $param_String_4,
					$param_arrayOf_ClassName_5, $param_String_6,
					$param_MAFAgentSystem_RMI_7 }, 5247400284317047811L);
		} catch (final java.lang.RuntimeException e) {
			throw e;
		} catch (final java.rmi.RemoteException e) {
			throw e;
		} catch (final java.lang.Exception e) {
			throw new java.rmi.UnexpectedException("undeclared checked exception", e);
		}
	}

	// implementation of receive_future_message(Name, byte[],
	// MAFAgentSystem_RMI)
	@Override
	public long receive_future_message(
	                                   final com.ibm.maf.Name $param_Name_1,
	                                   final byte[] $param_arrayOf_byte_2,
	                                   final com.ibm.maf.rmi.MAFAgentSystem_RMI $param_MAFAgentSystem_RMI_3)
	throws java.rmi.RemoteException {
		try {
			final Object $result = ref.invoke(this, $method_receive_future_message_11, new java.lang.Object[] {
					$param_Name_1, $param_arrayOf_byte_2,
					$param_MAFAgentSystem_RMI_3 }, 8372786121599055352L);

			return ((java.lang.Long) $result).longValue();
		} catch (final java.lang.RuntimeException e) {
			throw e;
		} catch (final java.rmi.RemoteException e) {
			throw e;
		} catch (final java.lang.Exception e) {
			throw new java.rmi.UnexpectedException("undeclared checked exception", e);
		}
	}

	// implementation of receive_future_reply(long, byte[])
	@Override
	public void receive_future_reply(
	                                 final long $param_long_1,
	                                 final byte[] $param_arrayOf_byte_2)
	throws java.rmi.RemoteException {
		try {
			ref.invoke(this, $method_receive_future_reply_12, new java.lang.Object[] {
					new java.lang.Long($param_long_1), $param_arrayOf_byte_2 }, 1543719985511141907L);
		} catch (final java.lang.RuntimeException e) {
			throw e;
		} catch (final java.rmi.RemoteException e) {
			throw e;
		} catch (final java.lang.Exception e) {
			throw new java.rmi.UnexpectedException("undeclared checked exception", e);
		}
	}

	// implementation of receive_message(Name, byte[])
	@Override
	public byte[] receive_message(
	                              final com.ibm.maf.Name $param_Name_1,
	                              final byte[] $param_arrayOf_byte_2)
	throws java.rmi.RemoteException {
		try {
			final Object $result = ref.invoke(this, $method_receive_message_13, new java.lang.Object[] {
					$param_Name_1, $param_arrayOf_byte_2 }, 2425421018900539852L);

			return ((byte[]) $result);
		} catch (final java.lang.RuntimeException e) {
			throw e;
		} catch (final java.rmi.RemoteException e) {
			throw e;
		} catch (final java.lang.Exception e) {
			throw new java.rmi.UnexpectedException("undeclared checked exception", e);
		}
	}

	// implementation of receive_oneway_message(Name, byte[])
	@Override
	public void receive_oneway_message(
	                                   final com.ibm.maf.Name $param_Name_1,
	                                   final byte[] $param_arrayOf_byte_2)
	throws java.rmi.RemoteException {
		try {
			ref.invoke(this, $method_receive_oneway_message_14, new java.lang.Object[] {
					$param_Name_1, $param_arrayOf_byte_2 }, -4074734472655664697L);
		} catch (final java.lang.RuntimeException e) {
			throw e;
		} catch (final java.rmi.RemoteException e) {
			throw e;
		} catch (final java.lang.Exception e) {
			throw new java.rmi.UnexpectedException("undeclared checked exception", e);
		}
	}

	// implementation of resume_agent(Name)
	@Override
	public void resume_agent(final com.ibm.maf.Name $param_Name_1)
	throws java.rmi.RemoteException {
		try {
			ref.invoke(this, $method_resume_agent_15, new java.lang.Object[] { $param_Name_1 }, -8848203470673221484L);
		} catch (final java.lang.RuntimeException e) {
			throw e;
		} catch (final java.rmi.RemoteException e) {
			throw e;
		} catch (final java.lang.Exception e) {
			throw new java.rmi.UnexpectedException("undeclared checked exception", e);
		}
	}

	// implementation of retract_agent(Name)
	@Override
	public byte[] retract_agent(final com.ibm.maf.Name $param_Name_1)
	throws java.rmi.RemoteException {
		try {
			final Object $result = ref.invoke(this, $method_retract_agent_16, new java.lang.Object[] { $param_Name_1 }, 7414295117841577261L);

			return ((byte[]) $result);
		} catch (final java.lang.RuntimeException e) {
			throw e;
		} catch (final java.rmi.RemoteException e) {
			throw e;
		} catch (final java.lang.Exception e) {
			throw new java.rmi.UnexpectedException("undeclared checked exception", e);
		}
	}

	// implementation of suspend_agent(Name)
	@Override
	public void suspend_agent(final com.ibm.maf.Name $param_Name_1)
	throws java.rmi.RemoteException {
		try {
			ref.invoke(this, $method_suspend_agent_17, new java.lang.Object[] { $param_Name_1 }, -4343813813978331740L);
		} catch (final java.lang.RuntimeException e) {
			throw e;
		} catch (final java.rmi.RemoteException e) {
			throw e;
		} catch (final java.lang.Exception e) {
			throw new java.rmi.UnexpectedException("undeclared checked exception", e);
		}
	}

	// implementation of terminate_agent(Name)
	@Override
	public void terminate_agent(final com.ibm.maf.Name $param_Name_1)
	throws java.rmi.RemoteException {
		try {
			ref.invoke(this, $method_terminate_agent_18, new java.lang.Object[] { $param_Name_1 }, 3985167905387372512L);
		} catch (final java.lang.RuntimeException e) {
			throw e;
		} catch (final java.rmi.RemoteException e) {
			throw e;
		} catch (final java.lang.Exception e) {
			throw new java.rmi.UnexpectedException("undeclared checked exception", e);
		}
	}
}
